# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Portfolio
tagline:          'Longer les lignes et passer les frontières en Afrique'
description:      'Longer les lignes et passer les frontières en Afrique'
url:              http://hyde.getpoole.com
baseurl:          https://kdjolar.github.io/portfolio/
baseurl_pages:    https://kdjolar.github.io/portfolio

author:
  name:           'Kossigari DJOLAR'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
